In [6]:
coords = [
    [ 68., 108.],
    [150.,  89.],
    [126., 155.],
    [ 86.,  80.],
    [142., 128.],
    [ 84., 134.],
    [117.,  76.],
    [  0.,   0.],
    [  0.,   0.]
]
coords

[[68.0, 108.0],
 [150.0, 89.0],
 [126.0, 155.0],
 [86.0, 80.0],
 [142.0, 128.0],
 [84.0, 134.0],
 [117.0, 76.0],
 [0.0, 0.0],
 [0.0, 0.0]]

In [24]:
import numpy as np

deviations = coords - np.array(coords[:7]).mean(axis=0)
deviations

array([[ -42.42857143,   -2.        ],
       [  39.57142857,  -21.        ],
       [  15.57142857,   45.        ],
       [ -24.42857143,  -30.        ],
       [  31.57142857,   18.        ],
       [ -26.42857143,   24.        ],
       [   6.57142857,  -34.        ],
       [-110.42857143, -110.        ],
       [-110.42857143, -110.        ]])

In [30]:
norms = np.linalg.norm(deviations, axis=1)
norms

array([ 42.47568332,  44.79841469,  47.61795237,  38.68791933,
        36.34219451,  35.69971131,  34.62923149, 155.86683222,
       155.86683222])

In [46]:
np.array([deviations.T[i] / norms for i in range(2)]).T

array([[-0.99889085, -0.04708576],
       [ 0.88332207, -0.46876659],
       [ 0.32700752,  0.94502174],
       [-0.63142634, -0.77543586],
       [ 0.86872653,  0.49529205],
       [-0.7403021 ,  0.67227434],
       [ 0.18976536, -0.98182947],
       [-0.70848024, -0.70573064],
       [-0.70848024, -0.70573064]])

In [90]:
coords = np.array([
    [ 68., 108.],
    [150.,  89.],
    [126., 155.],
    [ 86.,  80.],
    [142., 128.],
    [ 84., 134.],
    [117.,  76.],
    [  0.,   0.],
    [  0.,   0.]
])

deviations = coords - coords[coords != 0].reshape(-1, 2).mean(axis=0)
norms = np.linalg.norm(deviations, axis=1)
sin_cos = np.array([deviations.T[i] / norms for i in range(2)]).T
sin_cos[coords == 0] = 0
sin_cos

array([[-0.99889062, -0.04708575],
       [ 0.88332188, -0.46876648],
       [ 0.32700745,  0.94502154],
       [-0.63142618, -0.77543566],
       [ 0.86872629,  0.49529191],
       [-0.7403019 ,  0.67227416],
       [ 0.1897653 , -0.98182919],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

nan

In [78]:
sin_cos[coords == 0] = 0
sin_cos

array([[-0.99889085, -0.04708576],
       [ 0.88332207, -0.46876659],
       [ 0.32700752,  0.94502174],
       [-0.63142634, -0.77543586],
       [ 0.86872653,  0.49529205],
       [-0.7403021 ,  0.67227434],
       [ 0.18976536, -0.98182947],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [70]:
norms

array([ 42.47568332,  44.79841469,  47.61795237,  38.68791933,
        36.34219451,  35.69971131,  34.62923149, 155.86683222,
       155.86683222])

In [59]:
np.array(coords[:7]).mean(axis=0)

array([110.42857143, 110.        ])

In [60]:
coords = np.array(coords)
np.array(coords[:7]).mean(axis=0)

array([110.42857143, 110.        ])

In [61]:
coords = np.array(coords)
coords[coords != 0].mean(axis=0)

110.21428571428571

In [64]:
coords

array([[ 68., 108.],
       [150.,  89.],
       [126., 155.],
       [ 86.,  80.],
       [142., 128.],
       [ 84., 134.],
       [117.,  76.],
       [  0.,   0.],
       [  0.,   0.]])

array([110.42857143, 110.        ])